spring:
  application:
    name: api-passenger

server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:9001/eureka/
